import assert from 'node:assert/strict';
import test from 'node:test';

import {
  AUTOGENERATED_TAG_PREFIX,
  botKindOf,
  isAutogenerated,
  listComments,
  normalizeComments,
  parseGerritTimestamp,
} from '../src/core/comments.js';
import { parseGerritJson } from '../src/core/rest.js';
import { Session } from '../src/core/session.js';
import { PLACEHOLDER_TOKEN, fakeFetch, fixture } from './helpers.js';

const body = fixture('comments-body.txt');
const byFile = parseGerritJson(body, 'comments fixture');

test('a comment is machine-generated exactly when its tag carries the autogenerated prefix', () => {
  assert.equal(AUTOGENERATED_TAG_PREFIX, 'autogenerated:');
  assert.equal(isAutogenerated({ tag: 'autogenerated:ai-review' }), true);
  assert.equal(isAutogenerated({ tag: 'autogenerated:anything-at-all' }), true);
  assert.equal(isAutogenerated({ tag: 'not-autogenerated:ai-review' }), false);
  assert.equal(isAutogenerated({ tag: 'autogenerated' }), false, 'the colon is part of the convention');
  assert.equal(isAutogenerated({ tag: null }), false);
  assert.equal(isAutogenerated({}), false);
});

test('the tag suffix is the bot\'s self-declared kind', () => {
  assert.equal(botKindOf({ tag: 'autogenerated:ai-review' }), 'ai-review');
  assert.equal(botKindOf({ tag: 'autogenerated:some-future-bot' }), 'some-future-bot');
  assert.equal(botKindOf({ tag: 'autogenerated:' }), null);
  assert.equal(botKindOf({ tag: 'human-tag' }), null);
});

test('bot detection uses the tag, never the username', () => {
  // Same account, two comments: one tagged, one not. Only the tag decides.
  const comments = normalizeComments({
    'a.java': [
      { patch_set: 1, line: 1, message: 'tagged', author: { username: 'review-assistant' }, tag: 'autogenerated:ai-review' },
      { patch_set: 1, line: 2, message: 'untagged', author: { username: 'review-assistant' } },
    ],
  });
  assert.equal(comments[0].autogenerated, true);
  assert.equal(comments[1].autogenerated, false);
});

test('these are ordinary comments, not robot comments: no robot_id anywhere', () => {
  const comments = normalizeComments(byFile);
  assert.ok(comments.some((c) => c.autogenerated), 'the fixture has machine comments');
  for (const comment of comments) {
    assert.equal('robot_id' in /** @type {any} */ (comment), false);
    assert.equal(/** @type {any} */ (comment).robotId, undefined);
  }
  // ...and the recorded server body genuinely carries none.
  assert.equal(body.includes('robot_id'), false);
});

test('normalizeComments flattens the by-file shape and marks change-level comments', () => {
  const comments = normalizeComments(byFile);
  assert.equal(comments.length, 5);

  // Change-level first, then file/line order.
  assert.equal(comments[0].file, '/PATCHSET_LEVEL');
  assert.equal(comments[0].patchSetLevel, true);
  assert.equal(comments[0].line, null);

  assert.deepEqual(
    comments.slice(1).map((c) => [c.file, c.line]),
    [
      ['src/main/java/com/acme/widget/Queue.java', 42],
      ['src/main/java/com/acme/widget/Queue.java', 77],
      ['src/main/java/com/acme/widget/Retry.java', 5],
      ['src/main/java/com/acme/widget/Retry.java', 5],
    ],
  );

  const unresolved = comments.filter((c) => c.unresolved).map((c) => c.id);
  assert.deepEqual(unresolved, ['cmt0001', 'cmt0002']);

  const ranged = comments.find((c) => c.id === 'cmt0001');
  assert.deepEqual(ranged?.range, { startLine: 42, endLine: 42 });

  const reply = comments.find((c) => c.id === 'cmt0004');
  assert.equal(reply?.inReplyTo, 'cmt0003');
  assert.equal(reply?.patchSet, 3);

  // Two comments on the same file and line fall back to update order, so a reply
  // reads after the comment it answers.
  const retryThread = comments.filter((c) => c.file.endsWith('Retry.java')).map((c) => c.id);
  assert.deepEqual(retryThread, ['cmt0003', 'cmt0004']);
});

test('Gerrit\'s nanosecond UTC timestamps parse to dates', () => {
  const date = parseGerritTimestamp('2026-07-30 09:12:44.000000000');
  assert.equal(date?.toISOString(), '2026-07-30T09:12:44.000Z');
  assert.equal(parseGerritTimestamp(''), null);
  assert.equal(parseGerritTimestamp(null), null);
  assert.equal(parseGerritTimestamp('nonsense'), null);
});

/**
 * @param {{body?: string, status?: number}} [route]
 */
function sessionWithComments({ body: responseBody = body, status = 200 } = {}) {
  const fetchImpl = fakeFetch([{ path: '/comments', status, body: responseBody }]);
  const session = new Session({
    config: {
      host: 'gerrit.example.com',
      port: 29418,
      user: 'ada',
      project: 'acme/one',
      restBase: 'https://gerrit.example.com',
      severityPatterns: [],
      sources: {},
      configPath: '/nonexistent/config.json',
    },
    env: {},
    fetchImpl,
  });
  // Stand in for the credential store; no keyring or disk is touched.
  session.rememberToken(PLACEHOLDER_TOKEN);
  return { session, fetchImpl };
}

test('listComments returns every comment by default', async () => {
  const { session, fetchImpl } = sessionWithComments();
  const comments = await listComments(session, 184458);
  assert.equal(comments.length, 5);
  assert.equal(fetchImpl.calls.length, 1);
  assert.equal(fetchImpl.calls[0].url, 'https://gerrit.example.com/a/changes/184458/comments');
});

test('--bots keeps only autogenerated comments, whatever bot posted them', async () => {
  const { session } = sessionWithComments();
  const bots = await listComments(session, 184458, { botsOnly: true });
  assert.equal(bots.length, 3);
  assert.deepEqual(bots.map((c) => c.botKind), ['ai-review', 'ai-review', 'lint-suggest']);
  assert.ok(bots.every((c) => c.autogenerated));
});

test('the humans filter is the exact complement', async () => {
  const { session } = sessionWithComments();
  const humans = await listComments(session, 184458, { humansOnly: true });
  assert.deepEqual(humans.map((c) => c.author?.username), ['grace', 'alan']);
  assert.ok(humans.every((c) => !c.autogenerated));
});

test('with no severity configured, every comment comes back with severity null', async () => {
  const { session } = sessionWithComments();
  const comments = await listComments(session, 184458);
  assert.ok(comments.every((c) => c.severity === null), 'tier-3 must be a no-op by default');
});
