/**
 * Inline review comments.
 *
 * Only REST can reach these; `gerrit query` does not carry them.
 *
 * TIER 1 again: machine-generated comments are detected via Gerrit's own
 * convention, not via a username list. Every comment may carry a `tag`, and
 * Gerrit's convention for automation is `autogenerated:<kind>` (observed on a
 * live 3.14.1 server: `autogenerated:ai-review`). We filter on the
 * `autogenerated:` prefix and treat the suffix as the bot's self-declared kind,
 * so a bot we have never heard of is recognised the first time it posts.
 *
 * Note these are ordinary comments. They are *not* Gerrit's separate
 * robot-comments API and they carry no `robot_id` -- matching on `robot_id` finds
 * nothing on the observed server.
 */

import { restGetJson } from './rest.js';
import { annotateSeverity } from './severity.js';

/** Gerrit's convention for marking a comment as machine-generated. */
export const AUTOGENERATED_TAG_PREFIX = 'autogenerated:';

/** The pseudo-file Gerrit uses for change-level (non-inline) comments. */
export const PATCHSET_LEVEL_FILE = '/PATCHSET_LEVEL';

/**
 * @typedef {Object} Comment
 * @property {string} file            source path, or "/PATCHSET_LEVEL"
 * @property {boolean} patchSetLevel
 * @property {number|null} line       null for a file-level or change-level comment
 * @property {{startLine: number|null, endLine: number|null}|null} range
 * @property {number|null} patchSet
 * @property {string|null} id
 * @property {string|null} inReplyTo
 * @property {string} message
 * @property {Date|null} updated
 * @property {{name: string|null, username: string|null, email: string|null}|null} author
 * @property {string|null} tag
 * @property {boolean} autogenerated  the tag begins with "autogenerated:"
 * @property {string|null} botKind    the tag's suffix, e.g. "ai-review"
 * @property {boolean} unresolved
 * @property {string|null} [severity] present once tier-3 patterns are applied
 */

/**
 * Is this comment machine-generated, by Gerrit's own convention?
 *
 * @param {{tag?: string|null}} comment
 * @returns {boolean}
 */
export function isAutogenerated(comment) {
  return typeof comment?.tag === 'string' && comment.tag.startsWith(AUTOGENERATED_TAG_PREFIX);
}

/**
 * The bot's self-declared kind: the part after `autogenerated:`.
 *
 * @param {{tag?: string|null}} comment
 * @returns {string|null}
 */
export function botKindOf(comment) {
  if (!isAutogenerated(comment)) return null;
  return /** @type {string} */ (comment.tag).slice(AUTOGENERATED_TAG_PREFIX.length) || null;
}

/**
 * Flatten Gerrit's `{ "<file>": [CommentInfo, ...] }` shape into typed comments.
 *
 * @param {Record<string, any[]>} byFile
 * @returns {Comment[]}
 */
export function normalizeComments(byFile) {
  /** @type {Comment[]} */
  const out = [];
  for (const [file, list] of Object.entries(byFile ?? {})) {
    for (const raw of Array.isArray(list) ? list : []) {
      out.push({
        file,
        patchSetLevel: file === PATCHSET_LEVEL_FILE,
        line: Number.isFinite(Number(raw?.line)) ? Number(raw.line) : null,
        range: raw?.range
          ? {
            startLine: raw.range.start_line ?? null,
            endLine: raw.range.end_line ?? null,
          }
          : null,
        patchSet: Number.isFinite(Number(raw?.patch_set)) ? Number(raw.patch_set) : null,
        id: raw?.id ?? null,
        inReplyTo: raw?.in_reply_to ?? null,
        message: raw?.message ?? '',
        updated: parseGerritTimestamp(raw?.updated),
        author: raw?.author
          ? {
            name: raw.author.name ?? null,
            username: raw.author.username ?? null,
            email: raw.author.email ?? null,
          }
          : null,
        tag: raw?.tag ?? null,
        autogenerated: isAutogenerated(raw),
        botKind: botKindOf(raw),
        unresolved: raw?.unresolved === true,
      });
    }
  }
  return sortComments(out);
}

/**
 * Change-level comments first, then by file and line -- the order a reviewer
 * reads them in.
 *
 * @param {Comment[]} comments
 * @returns {Comment[]}
 */
export function sortComments(comments) {
  return [...comments].sort((a, b) => {
    if (a.patchSetLevel !== b.patchSetLevel) return a.patchSetLevel ? -1 : 1;
    if (a.file !== b.file) return a.file.localeCompare(b.file);
    if ((a.line ?? 0) !== (b.line ?? 0)) return (a.line ?? 0) - (b.line ?? 0);
    return (a.updated?.getTime() ?? 0) - (b.updated?.getTime() ?? 0);
  });
}

/**
 * Gerrit timestamps look like "2026-07-30 09:12:44.000000000" and are UTC.
 *
 * @param {unknown} value
 * @returns {Date|null}
 */
export function parseGerritTimestamp(value) {
  if (typeof value !== 'string' || !value.trim()) return null;
  const iso = `${value.trim().replace(' ', 'T').replace(/(\.\d{3})\d+$/, '$1')}Z`;
  const date = new Date(iso);
  return Number.isNaN(date.getTime()) ? null : date;
}

/**
 * Fetch the inline comments on a change.
 *
 * @param {import('./session.js').Session} session
 * @param {number|string} change   change number or full change id
 * @param {{botsOnly?: boolean, humansOnly?: boolean}} [opts]
 * @returns {Promise<Comment[]>}
 */
export async function listComments(session, change, { botsOnly = false, humansOnly = false } = {}) {
  const target = await session.restTarget();
  const byFile = /** @type {Record<string, any[]>} */ (
    await restGetJson(target, `/a/changes/${encodeURIComponent(String(change))}/comments`)
  );
  let comments = normalizeComments(byFile);
  if (botsOnly) comments = comments.filter((c) => c.autogenerated);
  if (humansOnly) comments = comments.filter((c) => !c.autogenerated);
  // Tier-3 enrichment. With no configured patterns this only adds severity: null.
  return annotateSeverity(comments, session.config.severityPatterns);
}
