// SPDX-License-Identifier: Apache-2.0

/**
 * Credential storage.
 *
 * What we store is a Gerrit *authentication token* -- generated by the user at
 * https://<host>/settings/#HTTPCredentials and revocable there at any time. We
 * deliberately refuse to store an LDAP/domain password even though a server with
 * `git_basic_auth_policy = HTTP_LDAP` would happily accept one: a token is
 * revocable and scoped to Gerrit, a domain password is neither. That refusal
 * lives in the CLI's prompt copy; this module only ever sees a token.
 *
 * Invariants, all security-relevant:
 *   - The token never appears in argv. `ps` is world-readable, so every backend
 *     receives it on the child process's stdin.
 *   - The token is never echoed, logged, or interpolated into an error message.
 *   - The backend chain degrades loudly, never silently:
 *         secret-tool (libsecret keyring)  ->  gpg to self  ->  0600 file
 *     and the caller is told which one was used, including the words "plaintext"
 *     when it is.
 *   - Directory mode 0700, file mode 0600.
 */

import fs from 'node:fs/promises';
import path from 'node:path';

import { configDir } from './config.js';
import { AuthError, GerritError } from './errors.js';
import { commandExists, runCommand } from './exec.js';

/** @typedef {'secret-tool'|'gpg'|'file'} Backend */

/**
 * @typedef {Object} StoreResult
 * @property {Backend} backend
 * @property {boolean} encryptedAtRest
 * @property {string|null} location      file path, or null for the keyring
 * @property {string|null} upgradeHint   how to get to encrypted storage
 * @property {string[]} degraded         backends that were tried and failed
 */

const SERVICE = 'gerrit-axi';

/**
 * Per-(host, user) credential paths, so one machine can talk to more than one
 * Gerrit. The basename is sanitised because host and user come from a git remote.
 *
 * @param {{host: string, user: string, env?: NodeJS.ProcessEnv}} id
 */
function paths({ host, user, env = process.env }) {
  const slug = `${host}_${user}`.replace(/[^A-Za-z0-9._-]/g, '_');
  const dir = path.join(configDir(env), 'credentials');
  return {
    dir,
    plain: path.join(dir, `${slug}.token`),
    gpg: path.join(dir, `${slug}.token.gpg`),
  };
}

/**
 * @param {{host: string, user: string}} id
 * @returns {string[]} secret-tool attribute pairs
 */
function attrs({ host, user }) {
  return ['service', SERVICE, 'host', host, 'account', user];
}

/**
 * Best storage backend available on this machine, without touching anything.
 *
 * @param {{env?: NodeJS.ProcessEnv, runner?: import('./exec.js').Runner}} [deps]
 * @returns {Promise<Backend>}
 */
export async function detectBackend({ env = process.env, runner = runCommand } = {}) {
  if (commandExists('secret-tool', env)) return 'secret-tool';
  if (commandExists('gpg', env) && (await hasGpgSecretKey(runner, env))) return 'gpg';
  return 'file';
}

/**
 * @param {import('./exec.js').Runner} runner
 * @param {NodeJS.ProcessEnv} [env]
 * @returns {Promise<boolean>}
 */
async function hasGpgSecretKey(runner, env = process.env) {
  try {
    const { code, stdout } = await runner('gpg', ['--list-secret-keys', '--with-colons'], {
      timeoutMs: 10_000,
      env,
    });
    return code === 0 && /^sec:/m.test(stdout);
  } catch {
    return false;
  }
}

/**
 * Persist a token. Callers must have verified it against the server first (see
 * `verifyToken` in rest.js) so an unverified secret never reaches disk.
 *
 * @param {string} token
 * @param {{host: string, user: string, env?: NodeJS.ProcessEnv, runner?: import('./exec.js').Runner}} id
 * @returns {Promise<StoreResult>}
 */
export async function saveToken(token, id) {
  if (!token) throw new GerritError('refusing to store an empty token', { code: 'EMPTY_TOKEN' });
  const { env = process.env, runner = runCommand } = id;
  const p = paths({ ...id, env });
  const degraded = [];

  await fs.mkdir(p.dir, { recursive: true, mode: 0o700 });
  await fs.chmod(configDir(env), 0o700).catch(() => {});
  await fs.chmod(p.dir, 0o700).catch(() => {});

  if (commandExists('secret-tool', env)) {
    const ok = await trySecretToolStore(token, { ...id, runner, env });
    if (ok) {
      return {
        backend: 'secret-tool',
        encryptedAtRest: true,
        location: null,
        upgradeHint: null,
        degraded,
      };
    }
    degraded.push('secret-tool (keyring unavailable)');
  }

  if (commandExists('gpg', env) && (await hasGpgSecretKey(runner, env))) {
    const ok = await tryGpgStore(token, p.gpg, runner, env);
    if (ok) {
      await fs.chmod(p.gpg, 0o600).catch(() => {});
      return {
        backend: 'gpg',
        encryptedAtRest: true,
        location: p.gpg,
        upgradeHint: null,
        degraded,
      };
    }
    degraded.push('gpg (encryption to self failed)');
  }

  // Last resort. The caller is required to say the word "plaintext" out loud.
  const handle = await fs.open(p.plain, 'w', 0o600);
  try {
    await handle.writeFile(`${token}\n`, 'utf8');
  } finally {
    await handle.close();
  }
  await fs.chmod(p.plain, 0o600);
  return {
    backend: 'file',
    encryptedAtRest: false,
    location: p.plain,
    upgradeHint: 'install libsecret-tools (provides secret-tool) or create a GPG key, then re-run: gerrit auth login',
    degraded,
  };
}

/**
 * @param {string} token
 * @param {{host: string, user: string, runner: import('./exec.js').Runner,
 *          env?: NodeJS.ProcessEnv}} id
 */
async function trySecretToolStore(token, id) {
  // id.env is the same environment commandExists probed, so the PATH agrees.
  try {
    const { code } = await id.runner(
      'secret-tool',
      ['store', `--label=Gerrit ${id.host} (${id.user})`, ...attrs(id)],
      { input: token, timeoutMs: 20_000, env: id.env }, // secret on stdin, never argv
    );
    return code === 0;
  } catch {
    return false;
  }
}

/**
 * @param {string} token
 * @param {string} outFile
 * @param {import('./exec.js').Runner} runner
 * @param {NodeJS.ProcessEnv} [env]
 */
async function tryGpgStore(token, outFile, runner, env = process.env) {
  try {
    const { code } = await runner(
      'gpg',
      ['--quiet', '--yes', '--encrypt', '--default-recipient-self', '--output', outFile],
      { input: token, timeoutMs: 30_000, env }, // secret on stdin, never argv
    );
    return code === 0;
  } catch {
    return false;
  }
}

/**
 * Load a stored token, trying the backends in the same order they are written.
 *
 * @param {{host: string, user: string, env?: NodeJS.ProcessEnv, runner?: import('./exec.js').Runner}} id
 * @returns {Promise<{token: string, backend: Backend, location: string|null}|null>}
 */
export async function loadToken(id) {
  const { env = process.env, runner = runCommand } = id;
  const p = paths({ ...id, env });

  if (commandExists('secret-tool', env)) {
    try {
      const { code, stdout } = await runner('secret-tool', ['lookup', ...attrs(id)], {
        timeoutMs: 20_000,
        env,
      });
      const token = stdout.replace(/[\r\n]+$/, '');
      if (code === 0 && token) return { token, backend: 'secret-tool', location: null };
    } catch {
      // fall through to the file backends
    }
  }

  if (await exists(p.gpg)) {
    try {
      const { code, stdout } = await runner('gpg', ['--quiet', '--decrypt', p.gpg], {
        timeoutMs: 60_000,
        env,
      });
      const token = stdout.replace(/[\r\n]+$/, '');
      if (code === 0 && token) return { token, backend: 'gpg', location: p.gpg };
    } catch {
      // fall through
    }
  }

  if (await exists(p.plain)) {
    const token = (await fs.readFile(p.plain, 'utf8')).replace(/[\r\n]+/g, '').trim();
    if (token) return { token, backend: 'file', location: p.plain };
  }

  return null;
}

/**
 * Whether a credential is stored, without decrypting one: a gpg file is only
 * checked for, so this never raises a pinentry prompt, and nothing it reads
 * leaves this function. For a caller that runs unattended, such as a session
 * start, and needs to know whether to say "not signed in" -- not whether the
 * token still works, which only the server can say (see `authStatus`).
 *
 * @param {{host: string, user: string, env?: NodeJS.ProcessEnv, runner?: import('./exec.js').Runner}} id
 * @returns {Promise<boolean>}
 */
export async function hasStoredToken(id) {
  const { env = process.env, runner = runCommand } = id;
  const p = paths({ ...id, env });

  if (commandExists('secret-tool', env)) {
    try {
      const { code, stdout } = await runner('secret-tool', ['lookup', ...attrs(id)], {
        timeoutMs: 5_000,
        env,
      });
      if (code === 0 && stdout.trim()) return true;
    } catch {
      // fall through to the file backends
    }
  }
  return (await exists(p.gpg)) || (await exists(p.plain));
}

/**
 * Like `loadToken`, but the absence of a credential is an error with a remedy.
 *
 * @param {{host: string, user: string, env?: NodeJS.ProcessEnv, runner?: import('./exec.js').Runner}} id
 * @returns {Promise<{token: string, backend: Backend, location: string|null}>}
 */
export async function requireToken(id) {
  const found = await loadToken(id);
  if (found) return found;
  throw new AuthError(`no stored Gerrit credential for ${id.user}@${id.host}`, {
    code: 'NO_CREDENTIAL',
    remedy: 'Run: gerrit auth login',
  });
}

/**
 * Remove the credential from every backend that holds one.
 *
 * @param {{host: string, user: string, env?: NodeJS.ProcessEnv, runner?: import('./exec.js').Runner}} id
 * @returns {Promise<{removed: Backend[]}>}
 */
export async function clearToken(id) {
  const { env = process.env, runner = runCommand } = id;
  const p = paths({ ...id, env });
  /** @type {Backend[]} */
  const removed = [];

  if (commandExists('secret-tool', env)) {
    try {
      const before = await runner('secret-tool', ['lookup', ...attrs(id)], { timeoutMs: 20_000, env });
      if (before.code === 0 && before.stdout.trim()) {
        const { code } = await runner('secret-tool', ['clear', ...attrs(id)], { timeoutMs: 20_000, env });
        if (code === 0) removed.push('secret-tool');
      }
    } catch {
      // nothing to remove
    }
  }
  for (const [file, backend] of /** @type {[string, Backend][]} */ ([[p.gpg, 'gpg'], [p.plain, 'file']])) {
    if (await exists(file)) {
      await fs.rm(file, { force: true });
      removed.push(backend);
    }
  }
  return { removed };
}

/**
 * @param {string} file
 * @returns {Promise<boolean>}
 */
async function exists(file) {
  try {
    await fs.access(file);
    return true;
  } catch {
    return false;
  }
}
