// SPDX-License-Identifier: Apache-2.0

/**
 * gerrit-axi core -- the library API.
 *
 * TWO RULES THIS MODULE EXISTS TO PROTECT:
 *
 *  1. Core returns data and never formats it. No tables, no colour, no column
 *     widths, no console.log. Nothing under src/core/ knows what a table looks
 *     like. Rendering lives in src/cli/ and src/axi/, and only there.
 *
 *  2. The second binary imports this module. It does not spawn the CLI and
 *     parse its output: both layers are Node, so there is no reason for a
 *     subprocess boundary between them. Everything below is therefore shaped as a
 *     callable API over typed objects, not as something to be screen-scraped.
 *
 * Typical use:
 *
 *     import { createSession, queryChanges, listComments } from 'gerrit-axi/core';
 *
 *     const session = await createSession();                 // tier-2 resolution
 *     const changes = await queryChanges(session, { kind: 'attention' });
 *     const blocked = changes.filter((c) => c.readiness.blocking.length > 0);
 *     const comments = await listComments(session, 184458, { botsOnly: true });
 *
 * ...and one change's whole review state -- the patch set the server has, who
 * voted and when, the stack, and the cover messages with the URLs they carry:
 *
 *     const [change] = await queryChangeDetails(session, [184458]);
 *
 * ...and the three writes, which are all there are -- nothing here can vote:
 *
 *     const publication = await publishChanges(session, { shape: 'stack', topic: 'retry' });
 *     const posted = await postChangeMessage(session, 184458, 'What the fix changed...');
 *     const merged = await submitChange(session, 184458);   // the server may refuse
 */

export { Session, createSession } from './session.js';

export {
  configDir,
  configPath,
  normalizeSeverityPatterns,
  readConfigFile,
  resolveConfig,
  saveConnection,
} from './config.js';

export {
  DEFAULT_SSH_PORT,
  acceptGerritRemote,
  gerritRepoEvidence,
  parseRemoteUrl,
  readGitRemoteUrl,
} from './remote.js';

export { authStatus, loginWithToken, logout, tokenSettingsUrl } from './auth.js';

export {
  clearToken,
  detectBackend,
  hasStoredToken,
  loadToken,
  requireToken,
  saveToken,
} from './credentials.js';

export {
  buildQuery,
  deriveMessages,
  deriveReadiness,
  deriveVotes,
  normalizeChange,
  queryChangeDetails,
  queryChangePage,
  queryChanges,
  sortByLastUpdatedDesc,
} from './changes.js';

export {
  AUTOGENERATED_TAG_PREFIX,
  PATCHSET_LEVEL_FILE,
  botKindOf,
  isAutogenerated,
  listComments,
  normalizeComments,
  parseGerritTimestamp,
  sortComments,
} from './comments.js';

export {
  annotateSeverity,
  classifySeverity,
  compileSeverityPatterns,
} from './severity.js';

export {
  XSSI_PREFIX,
  assertRestOk,
  basicAuthHeader,
  parseGerritJson,
  restGetJson,
  restGetRaw,
  restSubmit,
  stripXssiPrefix,
  verifyToken,
} from './rest.js';

export {
  DETAIL_QUERY_FLAGS,
  assertSafeConnection,
  assertSafeQuery,
  buildSshArgs,
  buildSshDestination,
  parseQueryOutput,
  runSsh,
  sshFailure,
  sshQuery,
} from './ssh.js';

export {
  buildPushArgs,
  footerChangeIds,
  parsePushResult,
  publishChanges,
  pushUrl,
  randomChangeId,
  stampChangeId,
} from './publish.js';

export { submitChange } from './submit.js';

export { buildMessageArgs, postChangeMessage, quoteForGerrit } from './message.js';

export { AuthError, ConfigError, GerritError, TransportError } from './errors.js';

export { commandExists, runCommand } from './exec.js';
