// SPDX-License-Identifier: Apache-2.0

/**
 * Publication: turning the commits on HEAD into Gerrit changes.
 *
 * Gerrit creates a change by being pushed to. `refs/for/<branch>` is a magic ref
 * that makes or updates one change per new commit and never writes the branch
 * itself, so publishing is one `git push`. What this module owns is getting the
 * commits into the shape that push needs. There are two shapes:
 *
 *   stack   every commit between the server's branch and HEAD becomes its own
 *           change, parent chain intact, all under one topic.
 *   squash  those commits become one change: HEAD's tree on top of the base,
 *           carrying the oldest commit's message.
 *
 * THE INVARIANT THIS MODULE EXISTS TO PROTECT: a change *is* its Change-Id. The
 * same Change-Id pushed again is a new patch set of the same change; a different
 * one is a different change, and the original's review history is orphaned. So a
 * Change-Id already in a commit message is carried verbatim, always. A commit
 * that has none gets one stamped into its message -- and the stamped commits are
 * written back to the local branch, because an id that lived only in what was
 * pushed would be generated afresh by the next publish, which is exactly the
 * orphaning above. The rewrite changes messages only, never a tree, so the
 * working tree and the index are left exactly as they were.
 *
 * The squash commit is built from the commits themselves -- their tree, message,
 * authors and dates -- so the same branch always squashes to the same commit, and
 * publishing it twice is answered by the server with "no new changes" rather
 * than an empty patch set.
 *
 * A push can carry more than a commit: Gerrit reads options off the magic ref,
 * and some of them vote or submit. `buildPushArgs` is the only place a push is
 * built, and the only option it can express is a topic.
 */

import { randomBytes } from 'node:crypto';

import { queryChanges } from './changes.js';
import { ConfigError, GerritError, TransportError } from './errors.js';

/** A Change-Id as Gerrit, and its commit-msg hook, write it. */
const CHANGE_ID = /^I[0-9a-f]{40}$/;

/** A footer line naming a Change-Id, whatever it holds. */
const CHANGE_ID_LINE = /^Change-Id:[ \t]*(.*?)[ \t]*$/;

/** One line of a trailer block: `Key: value`, or a continuation of one. */
const TRAILER_LINE = /^(?:[A-Za-z0-9][A-Za-z0-9-]*:[ \t]|[ \t])/;

/** A full object name, in a SHA-1 or a SHA-256 repository. */
const OBJECT_ID = /^[0-9a-f]{40}(?:[0-9a-f]{24})?$/;

/**
 * Branch and topic names this tool will put into a refspec. Deliberately narrower
 * than git allows: `%` and `,` are how Gerrit separates the options it reads off
 * the ref, and `:` ends the refspec, so none of them may arrive inside a name.
 */
const REF_NAME = /^[A-Za-z0-9][A-Za-z0-9._/-]*$/;

/** Gerrit's answer to a push every commit of which it already holds. */
const NO_NEW_CHANGES = 'no new changes';

/**
 * `git log` fields, NUL-separated, one record per commit. `%B` is the message
 * verbatim, which is what a Change-Id has to be read out of and written back to.
 */
const LOG_FIELDS = ['%H', '%T', '%P', '%an', '%ae', '%ad', '%cn', '%ce', '%cd', '%B'];

/**
 * @typedef {{name: string, email: string, date: string}} Ident
 *   `date` in git's raw form, "<epoch seconds> <zone>"
 */

/**
 * @typedef {Object} LocalCommit
 * @property {string} sha
 * @property {string} tree
 * @property {string[]} parents
 * @property {Ident} author
 * @property {Ident} committer
 * @property {string} message
 */

/**
 * @typedef {Object} Published
 * @property {string} commit     the commit pushed for this change
 * @property {string} changeId
 * @property {boolean} stamped   the Change-Id was generated by this publish
 * @property {string} subject
 * @property {import('./changes.js').Change|null} change
 *   the server's change for that Change-Id on that branch, read back after the
 *   push; null if the server did not return one
 * @property {boolean|null} isCurrentPatchSet
 *   is `commit` the change's current patch set on the server? null when there is
 *   no change to compare against
 */

/**
 * @typedef {Object} Publication
 * @property {'stack'|'squash'} shape
 * @property {string} branch
 * @property {string|null} topic
 * @property {string} base          the commit the published work sits on
 * @property {string} commit        the commit the push sent
 * @property {boolean} newPatchSets false when the server already held every commit
 * @property {string} head          local HEAD afterwards
 * @property {string|null} rewrittenFrom  local HEAD before, when Change-Ids were
 *   stamped into the branch; null when the branch was not touched
 * @property {Published[]} published  oldest first
 */

/**
 * The Change-Id lines in a message's footer -- its last paragraph, which is the
 * only place Gerrit reads one from. A message that is a single paragraph has no
 * footer at all.
 *
 * @param {string} message
 * @returns {string[]} the value of every Change-Id line, valid or not
 */
export function footerChangeIds(message) {
  return footerLines(message)
    .map((line) => CHANGE_ID_LINE.exec(line)?.[1])
    .filter((value) => value !== undefined);
}

/**
 * Add a Change-Id to a message that has none. It joins the footer when the last
 * paragraph is already a trailer block, and starts one otherwise; either way it
 * lands in the last paragraph, where Gerrit looks.
 *
 * @param {string} message
 * @param {string} changeId
 * @returns {string}
 */
export function stampChangeId(message, changeId) {
  if (!CHANGE_ID.test(changeId)) {
    throw new GerritError(`not a Change-Id: ${changeId}`, { code: 'BAD_CHANGE_ID' });
  }
  const body = String(message).replace(/\s+$/, '');
  const footer = footerLines(body);
  const joinsFooter = footer.length > 0 && footer.every((line) => TRAILER_LINE.test(line));
  return `${body}${joinsFooter ? '\n' : '\n\n'}Change-Id: ${changeId}\n`;
}

/**
 * A fresh Change-Id. Only uniqueness matters to Gerrit; the commit-msg hook
 * hashes the commit to get one, and random bytes serve as well.
 *
 * @returns {string}
 */
export function randomChangeId() {
  return `I${randomBytes(20).toString('hex')}`;
}

/**
 * @param {string} message
 * @returns {string[]}
 */
function footerLines(message) {
  const lines = String(message).replace(/\s+$/, '').split('\n');
  for (let i = lines.length - 1; i >= 0; i -= 1) {
    if (!lines[i].trim()) return lines.slice(i + 1);
  }
  return [];
}

/**
 * @param {string} message
 * @returns {string}
 */
function subjectOf(message) {
  return String(message).split('\n', 1)[0].trim();
}

/**
 * @param {string} name
 * @param {string} what   "branch" or "topic", for the message
 * @returns {string}
 */
function checkRefName(name, what) {
  if (
    typeof name !== 'string'
    || !REF_NAME.test(name)
    || name.includes('..')
    || name.includes('//')
    || name.endsWith('/')
    || name.endsWith('.')
    || name.endsWith('.lock')
  ) {
    throw new GerritError(`refusing to publish with this ${what} name: ${JSON.stringify(name)}`, {
      code: 'BAD_REF_NAME',
      remedy: `A ${what} name here is letters, digits, and . _ / - , starting with a letter or digit.`,
    });
  }
  return name;
}

/**
 * Where a publish pushes: Gerrit's SSH endpoint for the resolved project, the
 * same host, port and user every query goes to. Building it from the resolved
 * configuration rather than pushing to a remote by name means `--host` and the
 * other overrides steer a push exactly as they steer a query.
 *
 * @param {{host: string, port: number, user: string, project: string|null}} config
 * @returns {string}
 */
export function pushUrl({ host, port, user, project }) {
  if (!project) {
    throw new ConfigError('cannot determine the Gerrit project to publish to', {
      code: 'PROJECT_UNRESOLVED',
      remedy: [
        "Run this inside a repo whose 'origin' remote names the project,",
        'add "project" to the config file, or pass --project <project/path>.',
      ].join('\n'),
    });
  }
  // Each part is data read off a remote, the environment or a file. None may
  // look like an option to ssh, or break out of its place in the URL.
  const parts = /** @type {Array<[string, string, RegExp]>} */ ([
    ['host', host, /^-|[\s/@\0]/],
    ['user', user, /^-|[\s/@:\0]/],
    ['project', project, /^[-/]|[\s\0]/],
  ]);
  for (const [name, value, bad] of parts) {
    if (bad.test(String(value))) {
      throw new ConfigError(`refusing to publish to a ${name} of ${JSON.stringify(value)}`, {
        code: 'BAD_REMOTE_URL',
      });
    }
  }
  return `ssh://${user}@${host}:${port}/${project}`;
}

/**
 * The argv for the one push this tool makes: `commit` to `refs/for/<branch>`,
 * optionally with a topic. Exported so a test can pin it exactly.
 *
 * Nothing else can be expressed. Gerrit also reads a vote (`l=`), a submit, and
 * reviewers off the magic ref; none of them has a parameter here, and the branch
 * and topic are screened so that neither can smuggle one in.
 *
 * @param {string} url
 * @param {string} commit
 * @param {string} branch
 * @param {{topic?: string|null}} [opts]
 * @returns {string[]}
 */
export function buildPushArgs(url, commit, branch, { topic = null } = {}) {
  if (!OBJECT_ID.test(commit)) {
    throw new GerritError(`not a commit id: ${commit}`, { code: 'GIT_FAILED' });
  }
  checkRefName(branch, 'branch');
  if (topic !== null) checkRefName(topic, 'topic');
  return [
    // A configured push.pushOption would ride along on every push; an empty
    // value clears the list, so the server receives only what is built here.
    '-c', 'push.pushOption=',
    'push',
    '--porcelain',
    '--no-follow-tags',
    '--no-recurse-submodules',
    url,
    `${commit}:refs/for/${branch}${topic === null ? '' : `%topic=${topic}`}`,
  ];
}

/**
 * Read `git push --porcelain`: ref status on stdout, the server's own messages
 * on stderr behind `remote:`.
 *
 * A rejection is the server's decision and is reported in its words. The one
 * rejection that is not a failure is "no new changes": the server already holds
 * every commit that was pushed, which is the state a publish exists to reach.
 *
 * @param {{code: number|null, stdout: string, stderr: string}} result
 * @returns {{newPatchSets: boolean, messages: string[]}}
 */
export function parsePushResult({ code, stdout, stderr }) {
  const status = String(stdout ?? '').split('\n')
    .map((line) => /^(.)\t[^\t]*\t(.*)$/.exec(line))
    .find((match) => match !== null);
  const messages = String(stderr ?? '').split('\n')
    .map((line) => /^remote:\s*(.*?)\s*$/.exec(line)?.[1])
    .filter((line) => typeof line === 'string' && line !== '');

  if (status?.[1] === '!') {
    const reason = /\(([^)]*)\)\s*$/.exec(status[2])?.[1] ?? status[2].trim();
    if (reason === NO_NEW_CHANGES) return { newPatchSets: false, messages };
    throw new TransportError(`Gerrit rejected the push: ${reason}`, {
      code: 'PUSH_REJECTED',
      ...(messages.length > 0 ? { remedy: messages.join('\n') } : {}),
    });
  }
  if (code !== 0 || !status) {
    const said = String(stderr ?? '').split('\n')
      .map((line) => line.trim())
      .find((line) => line && !line.startsWith('remote:'));
    throw new TransportError(`the push to Gerrit failed: ${said || `exit ${code}`}`, {
      code: 'PUSH_FAILED',
      remedy: 'Check that your SSH key is registered with Gerrit and that the host is reachable.',
    });
  }
  return { newPatchSets: true, messages };
}

/**
 * @param {import('./session.js').Session} session
 * @param {string[]} args
 * @param {{input?: string, env?: NodeJS.ProcessEnv, timeoutMs?: number}} [opts]
 * @returns {Promise<import('./exec.js').RunResult>}
 */
async function git(session, args, { input, env, timeoutMs = 30_000 } = {}) {
  try {
    return await session.runner('git', ['-C', session.cwd, ...args], { input, env, timeoutMs });
  } catch (err) {
    throw new GerritError('could not run git', {
      code: 'GIT_FAILED',
      remedy: 'Is git installed and on PATH?',
      cause: err,
    });
  }
}

/**
 * `git`, where a non-zero exit is a failure.
 *
 * @param {import('./session.js').Session} session
 * @param {string[]} args
 * @param {{input?: string, env?: NodeJS.ProcessEnv, timeoutMs?: number}} [opts]
 * @returns {Promise<string>} stdout
 */
async function gitOk(session, args, opts) {
  const result = await git(session, args, opts);
  if (result.code !== 0) {
    throw new GerritError(`git ${args[0]} failed: ${firstLine(result.stderr) || `exit ${result.code}`}`, {
      code: 'GIT_FAILED',
    });
  }
  return result.stdout;
}

/**
 * The branch to propose against and its tip, as the server has them -- read off
 * the server rather than a remote-tracking ref, which is only as fresh as the
 * last fetch. With no branch named, the server's HEAD names its default branch.
 *
 * @param {import('./session.js').Session} session
 * @param {string} url
 * @param {string|null} branch
 * @returns {Promise<{branch: string, tip: string}>}
 */
async function serverBranch(session, url, branch) {
  const args = branch === null
    ? ['ls-remote', '--symref', url, 'HEAD']
    : ['ls-remote', url, `refs/heads/${branch}`];
  const result = await git(session, args, { timeoutMs: 60_000 });
  if (result.code !== 0) {
    throw new TransportError(
      `could not read the branches of ${url}: ${firstLine(result.stderr) || `exit ${result.code}`}`,
      {
        code: 'SSH_FAILED',
        remedy: 'Check that your SSH key is registered with Gerrit and that the host is reachable.',
      },
    );
  }

  let name = branch;
  let tip = null;
  for (const line of result.stdout.split('\n')) {
    const symref = /^ref: refs\/heads\/(\S+)\tHEAD$/.exec(line);
    if (symref) {
      if (branch === null) name = symref[1];
      continue;
    }
    const ref = /^([0-9a-f]{40,64})\t(\S+)$/.exec(line);
    if (ref && ref[2] === (branch === null ? 'HEAD' : `refs/heads/${branch}`)) tip = ref[1];
  }
  if (name === null || tip === null) {
    throw new GerritError(
      branch === null
        ? 'the server did not say which branch is its default'
        : `the server has no branch named ${branch}`,
      {
        code: 'NO_SUCH_BRANCH',
        remedy: branch === null
          ? 'Name the branch to propose against with --branch <branch>.'
          : 'Publishing proposes changes to a branch; it cannot create one.',
      },
    );
  }
  return { branch: checkRefName(name, 'branch'), tip };
}

/**
 * The commits to publish: everything on HEAD since it left the server's branch,
 * oldest first, as one straight line.
 *
 * @param {import('./session.js').Session} session
 * @param {{branch: string, tip: string}} server
 * @param {string} head
 * @returns {Promise<{base: string, commits: LocalCommit[]}>}
 */
async function localRange(session, server, head) {
  const known = await git(session, ['rev-parse', '--verify', '--quiet', `${server.tip}^{commit}`]);
  if (known.code === 1) {
    throw new GerritError(`this repository does not have the server's ${server.branch} yet`, {
      code: 'BASE_NOT_FETCHED',
      remedy: `Fetch it first, for example: git fetch origin ${server.branch}`,
    });
  }
  if (known.code !== 0) {
    throw new GerritError(`git rev-parse failed: ${firstLine(known.stderr) || `exit ${known.code}`}`, {
      code: 'GIT_FAILED',
    });
  }
  const merged = await git(session, ['merge-base', head, server.tip]);
  if (merged.code !== 0) {
    throw new GerritError(`HEAD shares no history with ${server.branch} on the server`, {
      code: 'UNRELATED_HISTORY',
    });
  }
  const base = merged.stdout.trim();

  const log = await gitOk(session, [
    'log', '-z', '--reverse', '--date=raw', '--no-show-signature',
    `--format=${LOG_FIELDS.join('%x00')}`, `${base}..${head}`,
  ]);
  const commits = parseLog(log);
  if (commits.length === 0) {
    throw new GerritError(`nothing to publish: HEAD is already on ${server.branch}`, {
      code: 'NOTHING_TO_PUBLISH',
    });
  }

  // A stack is a parent chain, and a stamped Change-Id has to be written back
  // through it, so the commits must form one line from the base up to HEAD.
  let parent = base;
  for (const commit of commits) {
    if (commit.parents.length !== 1 || commit.parents[0] !== parent) {
      throw new GerritError(`the commits to publish are not one straight line on ${server.branch}`, {
        code: 'NONLINEAR_HISTORY',
        remedy: `Rebase them onto ${server.branch} so that there is no merge among them.`,
      });
    }
    parent = commit.sha;
  }
  if (parent !== head) {
    throw new GerritError('the commits to publish do not end at HEAD', { code: 'NONLINEAR_HISTORY' });
  }
  return { base, commits };
}

/**
 * @param {string} stdout   `git log -z` output in LOG_FIELDS order
 * @returns {LocalCommit[]}
 */
export function parseLog(stdout) {
  const fields = String(stdout ?? '').split('\0');
  /** @type {LocalCommit[]} */
  const commits = [];
  for (let i = 0; i + LOG_FIELDS.length <= fields.length; i += LOG_FIELDS.length) {
    const [sha, tree, parents, an, ae, ad, cn, ce, cd, message] = fields.slice(i, i + LOG_FIELDS.length);
    commits.push({
      sha: sha.trim(),
      tree,
      parents: parents.split(' ').filter(Boolean),
      author: { name: an, email: ae, date: ad },
      committer: { name: cn, email: ce, date: cd },
      message,
    });
  }
  return commits;
}

/**
 * The environment that makes `git commit-tree` reproduce an identity and a date
 * exactly, so a rebuilt commit differs from its original only where it has to.
 *
 * @param {Ident} author
 * @param {Ident} committer
 * @returns {Record<string, string>}
 */
function identityEnv(author, committer) {
  return {
    GIT_AUTHOR_NAME: author.name,
    GIT_AUTHOR_EMAIL: author.email,
    GIT_AUTHOR_DATE: `@${author.date}`,
    GIT_COMMITTER_NAME: committer.name,
    GIT_COMMITTER_EMAIL: committer.email,
    GIT_COMMITTER_DATE: `@${committer.date}`,
  };
}

/**
 * @param {import('./session.js').Session} session
 * @param {string} tree
 * @param {string} parent
 * @param {string} message
 * @param {Record<string, string>} ident
 * @returns {Promise<string>} the new commit
 */
async function commitTree(session, tree, parent, message, ident) {
  const sha = (await gitOk(session, ['commit-tree', tree, '-p', parent], {
    input: message,
    env: { ...session.env, ...ident },
  })).trim();
  if (!OBJECT_ID.test(sha)) {
    throw new GerritError(`git commit-tree returned no commit id: ${sha}`, { code: 'GIT_FAILED' });
  }
  return sha;
}

/**
 * The Change-Id a commit already carries, or null when it carries none. Anything
 * Gerrit itself would refuse -- two Change-Id lines, or one that is malformed --
 * is refused here, before anything is rewritten or pushed.
 *
 * @param {LocalCommit} commit
 * @returns {string|null}
 */
function existingChangeId(commit) {
  const ids = footerChangeIds(commit.message);
  if (ids.length === 0) return null;
  if (ids.length === 1 && CHANGE_ID.test(ids[0])) return ids[0];
  throw new GerritError(
    `commit ${commit.sha.slice(0, 12)} (${subjectOf(commit.message)}) has ${
      ids.length === 1 ? `a malformed Change-Id: ${ids[0]}` : `${ids.length} Change-Id lines`
    }`,
    {
      code: 'BAD_CHANGE_ID',
      remedy: "A commit's footer carries exactly one line 'Change-Id: I' followed by 40 hex digits.",
    },
  );
}

/**
 * Publish the commits on HEAD to `refs/for/<branch>` as a stack of changes or as
 * one squashed change, then read back what the server made of them.
 *
 * @param {import('./session.js').Session} session
 * @param {{shape: 'stack'|'squash', branch?: string|null, topic?: string|null,
 *          newChangeId?: () => string}} opts
 *   `newChangeId` is the source of fresh Change-Ids, a parameter so a test can fix it
 * @returns {Promise<Publication>}
 */
export async function publishChanges(session, {
  shape,
  branch = null,
  topic = null,
  newChangeId = randomChangeId,
}) {
  if (shape !== 'stack' && shape !== 'squash') {
    throw new TypeError(`unknown publication shape: ${shape}`);
  }
  if (branch !== null) checkRefName(branch, 'branch');
  if (topic !== null) checkRefName(topic, 'topic');
  const url = pushUrl(session.config);

  // The repository is asked first, so a directory that is not one fails before
  // anything reaches the server.
  const head = (await gitOk(session, ['rev-parse', '--verify', 'HEAD^{commit}'])).trim();
  const server = await serverBranch(session, url, branch);
  const { base, commits } = await localRange(session, server, head);

  // Every commit of a stack becomes a change and needs a Change-Id; a squash
  // takes the oldest commit's message, so only that one does.
  const carriers = new Set(shape === 'stack' ? commits : commits.slice(0, 1));
  /** @type {Map<LocalCommit, {changeId: string, stamped: boolean}>} */
  const ids = new Map();
  for (const commit of carriers) {
    const existing = existingChangeId(commit);
    ids.set(commit, existing === null
      ? { changeId: newChangeId(), stamped: true }
      : { changeId: existing, stamped: false });
  }

  // Write any stamped Change-Id back into the branch. Commits below the first
  // stamped one are untouched; from there up each is rebuilt on its new parent,
  // with the same tree, identities and dates, and a new message only where one
  // was stamped.
  /** @type {LocalCommit[]} */
  const current = [];
  let parent = base;
  let rewriting = false;
  for (const commit of commits) {
    const id = ids.get(commit);
    rewriting ||= id?.stamped === true;
    if (!rewriting) {
      current.push(commit);
      parent = commit.sha;
      continue;
    }
    const message = id?.stamped ? stampChangeId(commit.message, id.changeId) : commit.message;
    const sha = await commitTree(session, commit.tree, parent, message,
      identityEnv(commit.author, commit.committer));
    const rebuilt = { ...commit, sha, parents: [parent], message };
    if (id) ids.set(rebuilt, id);
    current.push(rebuilt);
    parent = sha;
  }
  const newHead = parent;
  if (newHead !== head) {
    // Compare-and-swap: if HEAD moved while this ran, nothing is overwritten.
    const moved = await git(session, [
      'update-ref', '-m', 'gerrit-axi publish: stamp Change-Id', 'HEAD', newHead, head,
    ]);
    if (moved.code !== 0) {
      throw new GerritError('HEAD moved while publishing; nothing was pushed', {
        code: 'HEAD_MOVED',
        remedy: 'Run publish again.',
      });
    }
  }

  /** @type {Array<{commit: string, changeId: string, stamped: boolean, subject: string}>} */
  let toPublish;
  if (shape === 'stack') {
    toPublish = current.map((commit) => ({
      commit: commit.sha,
      ...(/** @type {{changeId: string, stamped: boolean}} */ (ids.get(commit))),
      subject: subjectOf(commit.message),
    }));
  } else {
    const oldest = current[0];
    const newest = current[current.length - 1];
    // One commit is already its own squash, and is pushed as it is.
    const commit = current.length === 1
      ? oldest.sha
      : await commitTree(session, newest.tree, base, oldest.message,
        identityEnv(oldest.author, newest.committer));
    toPublish = [{
      commit,
      ...(/** @type {{changeId: string, stamped: boolean}} */ (ids.get(oldest))),
      subject: subjectOf(oldest.message),
    }];
  }
  const pushed = toPublish[toPublish.length - 1].commit;

  const result = await git(session, buildPushArgs(url, pushed, server.branch, { topic }), {
    timeoutMs: 300_000,
  });
  const { newPatchSets } = parsePushResult(result);

  // Read back what the server now holds for each Change-Id on this branch. A
  // Change-Id is only unique per project and branch -- a cherry-pick carries its
  // original's -- so the query names both.
  const found = await queryChanges(
    session,
    `project:${session.config.project} branch:${server.branch} (${
      toPublish.map((p) => `change:${p.changeId}`).join(' OR ')
    })`,
    { limit: toPublish.length },
  );
  const byChangeId = new Map(found.map((change) => [change.id, change]));

  return {
    shape,
    branch: server.branch,
    topic,
    base,
    commit: pushed,
    newPatchSets,
    head: newHead,
    rewrittenFrom: newHead === head ? null : head,
    published: toPublish.map((entry) => {
      const change = byChangeId.get(entry.changeId) ?? null;
      return {
        ...entry,
        change,
        isCurrentPatchSet: change === null ? null : change.currentPatchSet?.revision === entry.commit,
      };
    }),
  };
}

/**
 * @param {string} text
 * @returns {string}
 */
function firstLine(text) {
  return String(text ?? '').split('\n').map((l) => l.trim()).filter(Boolean)[0] ?? '';
}
