/**
 * `gerrit comments <change> [--bots | --humans]`
 *
 * `--bots` filters on Gerrit's own `autogenerated:` tag convention rather than on
 * a list of bot usernames, so a bot nobody configured is still recognised.
 *
 * The severity column appears only when tier-3 `severity.patterns` are configured.
 * With the default (empty) configuration this prints raw comments and no severity
 * column at all.
 */

import { listComments } from '../../core/comments.js';
import { UsageError } from '../args.js';
import { commonPathPrefix } from '../render.js';

export const COMMENTS_USAGE = `usage: gerrit comments <change> [--bots | --humans]

  <change>   change number
  --bots     only machine-generated comments (Gerrit tag 'autogenerated:<kind>')
  --humans   only comments that are not machine-generated

These are the inline comments -- the ones attached to a file and a line. The
cover messages ("Patch Set 7: ...", a build result and the URL to read it,
"Uploaded patch set 8") are a different thing, and 'gerrit show <change>'
prints them.`;

/** Flags this command understands, for the argument parser. */
export const COMMENTS_FLAGS = {
  withValue: new Set(),
  boolean: new Set(['--bots', '--humans']),
};

/**
 * @param {{session: import('../../core/session.js').Session, args: import('../args.js').ParsedArgs,
 *          out: (line?: string) => void, err: (line?: string) => void,
 *          colorize: (code: string, text: string) => string}} ctx
 * @returns {Promise<number>}
 */
export async function runComments({ session, args, out, err, colorize }) {
  const [change, ...extra] = args.positional;
  if (!change) throw new UsageError(COMMENTS_USAGE);
  if (extra.length) throw new UsageError(`comments takes one change, got ${1 + extra.length}`);
  if (!/^[0-9]+$/.test(change)) {
    throw new UsageError(`not a change number: ${change}\n\n${COMMENTS_USAGE}`);
  }

  const botsOnly = args.flags['--bots'] === true;
  const humansOnly = args.flags['--humans'] === true;
  if (botsOnly && humansOnly) throw new UsageError('--bots and --humans are mutually exclusive');

  const comments = await listComments(session, change, { botsOnly, humansOnly });
  if (comments.length === 0) {
    out(botsOnly
      ? 'no machine-generated comments on this change'
      : humansOnly
        ? 'no human comments on this change'
        : 'no inline comments on this change');
    return 0;
  }

  // Only show severity if the local convention was actually configured.
  const anySeverity = comments.some((c) => c.severity);
  const prefix = commonPathPrefix(comments.filter((c) => !c.patchSetLevel).map((c) => c.file));
  if (prefix) err(colorize('dim', `files under ${prefix}`));

  for (const comment of comments) {
    const where = comment.patchSetLevel
      ? '(change)'
      : `${comment.file.slice(prefix.length)}:${comment.line ?? 'file'}`;

    const bits = [colorize('bold', where)];
    if (comment.patchSet !== null) bits.push(colorize('dim', `[ps${comment.patchSet}]`));
    if (anySeverity && comment.severity) bits.push(colorize('yellow', `[${comment.severity}]`));
    if (comment.unresolved) bits.push(colorize('red', 'UNRESOLVED'));
    bits.push(colorize('cyan', `<${describeAuthor(comment)}>`));

    out(bits.join('  '));
    for (const line of String(comment.message).split('\n')) out(`    ${line}`);
    out();
  }

  if (!anySeverity && session.config.severityPatterns.length > 0) {
    err(colorize('dim', 'no comment matched a configured severity pattern'));
  }
  return 0;
}

/**
 * Bots identify themselves through the tag, not the account, so prefer the
 * self-declared kind when there is one.
 *
 * @param {import('../../core/comments.js').Comment} comment
 * @returns {string}
 */
function describeAuthor(comment) {
  if (comment.autogenerated) {
    const who = comment.author?.username ?? comment.author?.name ?? 'bot';
    return `${who} · ${comment.botKind ?? 'autogenerated'}`;
  }
  return comment.author?.username ?? comment.author?.name ?? '?';
}
